### ISSUE TITLE
IDSU

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn_TODO#46]
- [x] IDSU Manager
- [ ] Gui for IDSU - Might need some help on how to set this out
- [x] Make them work
- [ ] Allow private ones

**Comment by Carbon-Ghost** [comment]
Here is a small reminder of IDSU properties ( tested on latest GT "Classic" version I had, non 5-6 basically ) : 

1 000 000 000 power storage, outputs 8192 packets
In later version, the power storage is 2x bigger, but that is OP, and was made so because IC2 experimental, so it's your decision guys about the size.
